[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "0.4.0"
update_changelog_on_bump = true
major_version_zero = false
annotated_tag = true
bump_message = "chore: release $current_version â†’ $new_version"
